// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Report struct {
	ReportID       int64
	ReportType     string
	ReporterUserID interface{}
	ReportedUserID interface{}
	GameID         interface{}
	Screen         string
	Category       string
	Description    string
	Resolved       bool
	CreatedAt      string
	ResolvedAt     interface{}
}

type User struct {
	PlayerID          int64
	Nickname          string
	Email             string
	PasswordHash      string
	Kills             sql.NullInt64
	Deaths            sql.NullInt64
	Wins              sql.NullInt64
	Losses            sql.NullInt64
	FlagCaptures      sql.NullInt64
	IsBanned          sql.NullBool
	IsAdmin           sql.NullBool
	SelectedCharacter sql.NullInt64
}
