// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    report_type,
    reporter_user_id,
    reported_user_id,
    game_id,
    screen,
    category,
    description
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING report_id, report_type, reporter_user_id, reported_user_id, game_id, screen, category, description, resolved, created_at, resolved_at
`

type CreateReportParams struct {
	ReportType     string
	ReporterUserID interface{}
	ReportedUserID interface{}
	GameID         interface{}
	Screen         string
	Category       string
	Description    string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReportType,
		arg.ReporterUserID,
		arg.ReportedUserID,
		arg.GameID,
		arg.Screen,
		arg.Category,
		arg.Description,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ReportType,
		&i.ReporterUserID,
		&i.ReportedUserID,
		&i.GameID,
		&i.Screen,
		&i.Category,
		&i.Description,
		&i.Resolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nickname, email, password_hash)
VALUES (?, ?, ?)
RETURNING player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character
`

type CreateUserParams struct {
	Nickname     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Nickname, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character FROM users
WHERE player_id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, playerID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, playerID)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}

const getUserByNickname = `-- name: GetUserByNickname :one
SELECT player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character FROM users
WHERE nickname = ? LIMIT 1
`

func (q *Queries) GetUserByNickname(ctx context.Context, nickname string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByNickname, nickname)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT report_id, report_type, reporter_user_id, reported_user_id, game_id, screen, category, description, resolved, created_at, resolved_at FROM reports
ORDER BY resolved ASC, report_id DESC
`

func (q *Queries) ListReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ReportID,
			&i.ReportType,
			&i.ReporterUserID,
			&i.ReportedUserID,
			&i.GameID,
			&i.Screen,
			&i.Category,
			&i.Description,
			&i.Resolved,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportResolved = `-- name: MarkReportResolved :one
UPDATE reports
SET resolved = 1,
    resolved_at = CURRENT_TIMESTAMP
WHERE report_id = ?
RETURNING report_id, report_type, reporter_user_id, reported_user_id, game_id, screen, category, description, resolved, created_at, resolved_at
`

func (q *Queries) MarkReportResolved(ctx context.Context, reportID int64) (Report, error) {
	row := q.db.QueryRowContext(ctx, markReportResolved, reportID)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ReportType,
		&i.ReporterUserID,
		&i.ReportedUserID,
		&i.GameID,
		&i.Screen,
		&i.Category,
		&i.Description,
		&i.Resolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateUserNickname = `-- name: UpdateUserNickname :one
UPDATE users
SET nickname = ?
WHERE player_id = ?
RETURNING player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character
`

type UpdateUserNicknameParams struct {
	Nickname string
	PlayerID int64
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserNickname, arg.Nickname, arg.PlayerID)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = ?
WHERE player_id = ?
RETURNING player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	PlayerID     int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.PasswordHash, arg.PlayerID)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}

const updateUserSkin = `-- name: UpdateUserSkin :one
UPDATE users
SET selected_character = ?
WHERE player_id = ?
RETURNING player_id, nickname, email, password_hash, kills, deaths, wins, losses, flag_captures, is_banned, is_admin, selected_character
`

type UpdateUserSkinParams struct {
	SelectedCharacter sql.NullInt64
	PlayerID          int64
}

func (q *Queries) UpdateUserSkin(ctx context.Context, arg UpdateUserSkinParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserSkin, arg.SelectedCharacter, arg.PlayerID)
	var i User
	err := row.Scan(
		&i.PlayerID,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.Kills,
		&i.Deaths,
		&i.Wins,
		&i.Losses,
		&i.FlagCaptures,
		&i.IsBanned,
		&i.IsAdmin,
		&i.SelectedCharacter,
	)
	return i, err
}
